export const cuisineList = [
  { id: 1, name: "american" },
  { id: 2, name: "bbq" },
  { id: 3, name: "breakfast" },
  { id: 4, name: "burgers" },
  { id: 5, name: "cafe" },
  { id: 6, name: "chinese" },
  { id: 7, name: "desserts" },
  { id: 8, name: "french" },
  { id: 9, name: "greek" },
  { id: 10, name: "healthy" },
  { id: 11, name: "indian" },
  { id: 12, name: "italian" },
  { id: 13, name: "japanese" },
  { id: 14, name: "mexican" },
  { id: 15, name: "noodles" },
  { id: 16, name: "organic" },
  { id: 17, name: "pasta" },
  { id: 18, name: "pizza" },
  { id: 19, name: "salads" },
  { id: 20, name: "seafood" },
  { id: 21, name: "spanish" },
  { id: 22, name: "steak" },
  { id: 23, name: "sushi" },
  { id: 24, name: "tacos" },
  { id: 25, name: "tapas" },
  { id: 26, name: "vegan" },
] as const;
